/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik

Finite fiber/Fourier arguments adapted from Lech Mazur, Copyright 2026 Lech Mazur,
under Apache License 2.0. The original LICENSE and NOTICE are retained at
research/sources/mazur_830b9d3f38f2/. This version uses the actual local projection,
explicit Mathlib imports and the pinned module format.
-/
module

public import WordCertDensity.Analytic.FiberAverage
public import Mathlib.Analysis.Fourier.ZMod
import Mathlib.GroupTheory.Coset.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Push
import Mathlib.Tactic.Ring

/-!
# Fourier filtering by the actual ternary projection

The local projection kernel is generated by the lower ternary modulus.
Its character annihilator identifies exactly the retained frequencies.
-/

@[expose] public section

namespace WordCertDensity
namespace FiniteFourier

open Reference

/-- The projection kernel is generated by the lower-level modulus. -/
theorem projection_kernel_eq_zmultiples {m n : ℕ} (h : m ≤ n) :
    (project h).toAddMonoidHom.ker =
      AddSubgroup.zmultiples ((3 ^ m : ℕ) : ZMod (3 ^ n)) := by
  ext x
  constructor
  · intro hx
    rw [AddMonoidHom.mem_ker] at hx
    change project h x = 0 at hx
    have hxcast : project h x = (x.val : ZMod (3 ^ m)) := by
      conv_lhs => rw [← ZMod.natCast_zmod_val x]
      exact project_natCast h x.val
    rw [hxcast] at hx
    obtain ⟨k, hk⟩ := (ZMod.natCast_eq_zero_iff x.val (3 ^ m)).mp hx
    rw [AddSubgroup.mem_zmultiples_iff]
    refine ⟨(k : ℤ), ?_⟩
    rw [← ZMod.natCast_zmod_val x, hk]
    push_cast
    simp [mul_comm]
  · intro hx
    rw [AddSubgroup.mem_zmultiples_iff] at hx
    obtain ⟨k, hk⟩ := hx
    rw [AddMonoidHom.mem_ker, ← hk, map_zsmul]
    change k • project h ((3 ^ m : ℕ) : ZMod (3 ^ n)) = 0
    rw [project_natCast]
    simp

/-- A sum on the actual projection fiber is a translated sum over its kernel. -/
theorem fiber_sum_eq_sum_kernel {m n : ℕ} (h : m ≤ n)
    (p : ZMod (3 ^ n) → ℝ) (x : ZMod (3 ^ n)) :
    (∑ y ∈ fiber h (project h x), p y) =
      ∑ z : (project h).toAddMonoidHom.ker, p (x + z.1) := by
  classical
  let f := (project h).toAddMonoidHom
  calc
    _ = ∑ y : f ⁻¹' {f x}, p y.1 := by
      apply Finset.sum_subtype
      simp [fiber, f]
    _ = _ := by
      apply Fintype.sum_equiv (f.fiberEquivKer x)
      intro y
      change p y.1 = p (x + (f.fiberEquivKer x y).1)
      rw [AddMonoidHom.fiberEquivKer_apply]
      simp

/-- The actual projection kernel has the same size as every projection fiber. -/
theorem card_projection_kernel {m n : ℕ} (h : m ≤ n) :
    Fintype.card (project h).toAddMonoidHom.ker = 3 ^ (n - m) := by
  classical
  have hsum := fiber_sum_eq_sum_kernel h (fun _ => (1 : ℝ)) 0
  simp only [Finset.sum_const, nsmul_eq_mul, mul_one, card_fiber,
    Finset.card_univ] at hsum
  exact_mod_cast hsum.symm


/-- Divisibility by a ternary power is the same for a residue and its natural representative. -/
theorem three_pow_dvd_iff_dvd_val {q n : ℕ} (h : q ≤ n) (ξ : ZMod (3 ^ n)) :
    (3 : ZMod (3 ^ n)) ^ q ∣ ξ ↔ 3 ^ q ∣ ξ.val := by
  constructor
  · rintro ⟨η, hη⟩
    have hcast : (ξ.val : ZMod (3 ^ n)) = ((3 ^ q * η.val : ℕ) : ZMod (3 ^ n)) := by
      calc
        _ = ξ := ZMod.natCast_zmod_val ξ
        _ = (3 : ZMod (3 ^ n)) ^ q * η := hη
        _ = _ := by simp only [Nat.cast_mul, Nat.cast_pow, Nat.cast_ofNat,
          ZMod.natCast_zmod_val]
    have hmod := (ZMod.natCast_eq_natCast_iff ξ.val (3 ^ q * η.val) (3 ^ n)).mp hcast
    exact (hmod.dvd_iff (Nat.pow_dvd_pow 3 h)).mpr (dvd_mul_right (3 ^ q) η.val)
  · rintro ⟨η, hη⟩
    refine ⟨(η : ZMod (3 ^ n)), ?_⟩
    rw [← ZMod.natCast_zmod_val ξ, hη]
    simp only [Nat.cast_mul, Nat.cast_pow, Nat.cast_ofNat]

/-- The kernel annihilator consists exactly of the retained ternary-power frequencies. -/
theorem retained_frequency_iff {m n : ℕ} (h : m ≤ n) (ξ : ZMod (3 ^ n)) :
    ((3 ^ m : ℕ) : ZMod (3 ^ n)) * ξ = 0 ↔ (3 : ZMod (3 ^ n)) ^ (n - m) ∣ ξ := by
  rw [three_pow_dvd_iff_dvd_val (Nat.sub_le n m)]
  conv_lhs =>
    rw [← ZMod.natCast_zmod_val ξ, ← Nat.cast_mul, ZMod.natCast_eq_zero_iff]
  have hpow : 3 ^ n = 3 ^ m * 3 ^ (n - m) := by
    rw [← pow_add, Nat.add_sub_of_le h]
  generalize ξ.val = k
  rw [hpow, Nat.mul_dvd_mul_iff_left (pow_pos (by norm_num) m)]

private noncomputable def kernelChar {m n : ℕ} (h : m ≤ n) (ξ : ZMod (3 ^ n)) :
    AddChar (project h).toAddMonoidHom.ker ℂ :=
  ((ZMod.stdAddChar (N := 3 ^ n)).mulShift ξ).compAddMonoidHom
    (project h).toAddMonoidHom.ker.subtype

private theorem kernelChar_apply {m n : ℕ} (h : m ≤ n) (ξ : ZMod (3 ^ n))
    (z : (project h).toAddMonoidHom.ker) :
    kernelChar h ξ z = ZMod.stdAddChar (z.1 * ξ) := by
  simp only [kernelChar, AddChar.compAddMonoidHom_apply, AddChar.mulShift_apply,
    AddSubgroup.subtype_apply]
  rw [mul_comm]

private theorem kernelChar_eq_one_iff {m n : ℕ} (h : m ≤ n) (ξ : ZMod (3 ^ n)) :
    kernelChar h ξ = 1 ↔ ((3 ^ m : ℕ) : ZMod (3 ^ n)) * ξ = 0 := by
  let f := (project h).toAddMonoidHom
  let g : ZMod (3 ^ n) := ((3 ^ m : ℕ) : ZMod (3 ^ n))
  constructor
  · intro hchar
    have hg : g ∈ f.ker := by
      rw [projection_kernel_eq_zmultiples h]
      exact AddSubgroup.mem_zmultiples g
    have hv' : ZMod.stdAddChar (g * ξ) = 1 :=
      (kernelChar_apply h ξ (⟨g, hg⟩ : f.ker)).symm.trans
        ((DFunLike.congr_fun hchar (⟨g, hg⟩ : f.ker)).trans (AddChar.one_apply _))
    exact ((ZMod.isPrimitive_stdAddChar (3 ^ n)).zmod_char_eq_one_iff
      (3 ^ n) (g * ξ)).mp hv'
  · intro hret
    rw [AddChar.eq_one_iff]
    intro z
    have hz : z.1 ∈ AddSubgroup.zmultiples g := by
      rw [← projection_kernel_eq_zmultiples h]
      exact z.2
    obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp hz
    rw [kernelChar_apply, ← hk, zsmul_eq_mul, mul_assoc, hret, mul_zero]
    exact AddChar.map_zero_eq_one _

/-- The character sum on the actual projection kernel is its size or zero. -/
theorem sum_character_kernel {m n : ℕ} (h : m ≤ n) (ξ : ZMod (3 ^ n)) :
    (∑ z : (project h).toAddMonoidHom.ker, ZMod.stdAddChar (z.1 * ξ)) =
      if ((3 ^ m : ℕ) : ZMod (3 ^ n)) * ξ = 0 then
        (Fintype.card (project h).toAddMonoidHom.ker : ℂ) else 0 := by
  classical
  split_ifs with hret
  · simpa only [kernelChar_apply] using
      AddChar.sum_eq_card_of_eq_one ((kernelChar_eq_one_iff h ξ).mpr hret)
  · simpa only [kernelChar_apply] using
      AddChar.sum_eq_zero_of_ne_one (mt (kernelChar_eq_one_iff h ξ).mp hret)

private theorem dft_translate {N : ℕ} [NeZero N] (p : ZMod N → ℝ) (z ξ : ZMod N) :
    ZMod.dft (fun x => (p (x + z) : ℂ)) ξ =
      ZMod.stdAddChar (z * ξ) * ZMod.dft (fun x => (p x : ℂ)) ξ := by
  rw [ZMod.dft_apply, ZMod.dft_apply]
  simp only [smul_eq_mul]
  calc
    _ = ∑ x, ZMod.stdAddChar (-((x - z) * ξ)) * (p x : ℂ) := by
      apply Fintype.sum_equiv (Equiv.addRight z)
      intro x
      simp
    _ = _ := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro x _
      rw [show -((x - z) * ξ) = z * ξ + -(x * ξ) by ring,
        AddChar.map_add_eq_mul]
      ring

/-- The DFT of a fiber sum is multiplied by the exact kernel character sum. -/
theorem dft_fiber_sum {m n : ℕ} (h : m ≤ n) (p : ZMod (3 ^ n) → ℝ)
    (ξ : ZMod (3 ^ n)) :
    ZMod.dft (fun x => ((∑ y ∈ fiber h (project h x), p y : ℝ) : ℂ)) ξ =
      (∑ z : (project h).toAddMonoidHom.ker, ZMod.stdAddChar (z.1 * ξ)) *
        ZMod.dft (fun x => (p x : ℂ)) ξ := by
  rw [ZMod.dft_apply]
  simp only [smul_eq_mul]
  simp_rw [fiber_sum_eq_sum_kernel h]
  simp only [Complex.ofReal_sum]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro z _
  exact dft_translate p z.1 ξ

/-- Fiber averaging retains the kernel annihilator and kills its complement. -/
theorem dft_fiberAverage {m n : ℕ} (h : m ≤ n) (p : ZMod (3 ^ n) → ℝ)
    (ξ : ZMod (3 ^ n)) :
    ZMod.dft (fun x => (fiberAverage h p x : ℂ)) ξ =
      if ((3 ^ m : ℕ) : ZMod (3 ^ n)) * ξ = 0 then
        ZMod.dft (fun x => (p x : ℂ)) ξ else 0 := by
  calc
    _ = ZMod.dft (fun x => ((∑ y ∈ fiber h (project h x), p y : ℝ) : ℂ)) ξ /
        (3 : ℂ) ^ (n - m) := by
      rw [ZMod.dft_apply, ZMod.dft_apply]
      simp only [fiberAverage, Complex.ofReal_div, Complex.ofReal_pow,
        Complex.ofReal_ofNat, smul_eq_mul]
      rw [Finset.sum_div]
      simp only [mul_div_assoc]
    _ = _ := by
      rw [dft_fiber_sum, sum_character_kernel, card_projection_kernel]
      split_ifs <;> simp

/-- A ternary-power multiple frequency is preserved by the actual fiber average. -/
theorem dft_fiberAverage_of_dvd {m n : ℕ} (h : m ≤ n) (p : ZMod (3 ^ n) → ℝ)
    (ξ : ZMod (3 ^ n)) (hξ : (3 : ZMod (3 ^ n)) ^ (n - m) ∣ ξ) :
    ZMod.dft (fun x => (fiberAverage h p x : ℂ)) ξ =
      ZMod.dft (fun x => (p x : ℂ)) ξ := by
  rw [dft_fiberAverage, if_pos ((retained_frequency_iff h ξ).mpr hξ)]

/-- Frequencies outside the retained multiples are killed by the actual fiber average. -/
theorem dft_fiberAverage_of_not_dvd {m n : ℕ} (h : m ≤ n) (p : ZMod (3 ^ n) → ℝ)
    (ξ : ZMod (3 ^ n)) (hξ : ¬ (3 : ZMod (3 ^ n)) ^ (n - m) ∣ ξ) :
    ZMod.dft (fun x => (fiberAverage h p x : ℂ)) ξ = 0 := by
  rw [dft_fiberAverage, if_neg (mt (retained_frequency_iff h ξ).mp hξ)]

/-- The residual after averaging keeps precisely the complementary frequencies. -/
theorem dft_fiberDifference {m n : ℕ} (h : m ≤ n) (p : ZMod (3 ^ n) → ℝ)
    (ξ : ZMod (3 ^ n)) :
    ZMod.dft (fun x => ((p x - fiberAverage h p x : ℝ) : ℂ)) ξ =
      if ((3 ^ m : ℕ) : ZMod (3 ^ n)) * ξ = 0 then 0
        else ZMod.dft (fun x => (p x : ℂ)) ξ := by
  calc
    _ = ZMod.dft (fun x => (p x : ℂ)) ξ -
        ZMod.dft (fun x => (fiberAverage h p x : ℂ)) ξ := by
      rw [ZMod.dft_apply, ZMod.dft_apply, ZMod.dft_apply]
      simp only [smul_eq_mul, Complex.ofReal_sub, mul_sub, Finset.sum_sub_distrib]
    _ = _ := by
      rw [dft_fiberAverage]
      split_ifs <;> simp

end FiniteFourier
end WordCertDensity
