import Solution

/-! Axiom reports for all eighteen selected Phase 1 declarations. -/

#print axioms CollatzWordCert.collatz_convergence_positive_lower_density
#print axioms CollatzWordCert.collatz_convergence_depth_eleven_density_bound
#print axioms CollatzWordCert.collatz_logarithmic_threshold_lt_10431_div_1000
#print axioms CollatzWordCert.collatz_hitting_positive_lower_density
#print axioms CollatzWordCert.collatz_hitting_depth_eleven_density_bound
#print axioms CollatzWordCert.collatz_hitting_positive_density_iff_target_not_divisible_by_three
#print axioms CollatzWordCert.collatz_canonical_root_reaches_one_with_positive_density
#print axioms CollatzWordCert.collatz_convergence_density_with_vanishing_clock_loss
#print axioms CollatzWordCert.collatz_hitting_density_with_vanishing_clock_loss
#print axioms CollatzWordCert.collatz_convergence_fractional_density_bound
#print axioms CollatzWordCert.collatz_hitting_fractional_density_bound
#print axioms CollatzWordCert.fan_profile_eq_optimal_allocation
#print axioms CollatzWordCert.fan_profile_ge_real_moment_bound
#print axioms CollatzWordCert.collatz_convergence_profile_density_bound
#print axioms CollatzWordCert.collatz_hitting_profile_density_bound
#print axioms CollatzWordCert.reference_entropy_increment_bounds
#print axioms CollatzWordCert.reference_entropy_tends_to_finite_limit_with_tail_bound
#print axioms CollatzWordCert.reference_entropy_div_level_tends_to_zero
