/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module
public import WordCertDensity.Certificates.DepthNine.Cap0
public import WordCertDensity.Certificates.DepthNine.Cap1
public import WordCertDensity.Certificates.DepthNine.Cap2
public import WordCertDensity.Certificates.DepthNine.Cap3
public import WordCertDensity.Certificates.DepthNine.Cap4
public import WordCertDensity.Certificates.DepthNine.Cap5
public import WordCertDensity.Certificates.DepthNine.Cap6
public import WordCertDensity.Certificates.DepthNine.Cap7
public import WordCertDensity.Certificates.DepthNine.Cap8
public import WordCertDensity.Certificates.DepthNine.Cap9
public import WordCertDensity.Certificates.DepthNine.Cap10
public import WordCertDensity.Certificates.DepthNine.Cap11
public import WordCertDensity.Certificates.DepthNine.Cap12
public import WordCertDensity.Certificates.DepthNine.Cap13
public import WordCertDensity.Certificates.DepthNine.Cap14
public import WordCertDensity.Certificates.DepthNine.Cap15
/-! # Depth-nine integer certificate component -/

@[expose] public section
namespace WordCertDensity.Certificates
/-- Exact finite certificate for the stated depth-nine range or bound. -/
theorem levelNine_cap : levelNine.allLE 15784016688259364 = true := by
  simp only [
    levelNineEvenEvenEvenEvenEvenEven,
    levelNineEvenEvenEvenEvenEvenOdd,
    levelNineEvenEvenEvenEvenEven,
    levelNineEvenEvenEvenEvenOddEven,
    levelNineEvenEvenEvenEvenOddOdd,
    levelNineEvenEvenEvenEvenOdd,
    levelNineEvenEvenEvenEven,
    levelNineEvenEvenEvenOddEvenEven,
    levelNineEvenEvenEvenOddEvenOdd,
    levelNineEvenEvenEvenOddEven,
    levelNineEvenEvenEvenOddOddEven,
    levelNineEvenEvenEvenOddOddOdd,
    levelNineEvenEvenEvenOddOdd,
    levelNineEvenEvenEvenOdd,
    levelNineEvenEvenEven,
    levelNineEvenEvenOddEvenEvenEven,
    levelNineEvenEvenOddEvenEvenOdd,
    levelNineEvenEvenOddEvenEven,
    levelNineEvenEvenOddEvenOddEven,
    levelNineEvenEvenOddEvenOddOdd,
    levelNineEvenEvenOddEvenOdd,
    levelNineEvenEvenOddEven,
    levelNineEvenEvenOddOddEvenEven,
    levelNineEvenEvenOddOddEvenOdd,
    levelNineEvenEvenOddOddEven,
    levelNineEvenEvenOddOddOddEven,
    levelNineEvenEvenOddOddOddOdd,
    levelNineEvenEvenOddOddOdd,
    levelNineEvenEvenOddOdd,
    levelNineEvenEvenOdd,
    levelNineEvenEven,
    levelNineEvenOddEvenEvenEvenEven,
    levelNineEvenOddEvenEvenEvenOdd,
    levelNineEvenOddEvenEvenEven,
    levelNineEvenOddEvenEvenOddEven,
    levelNineEvenOddEvenEvenOddOdd,
    levelNineEvenOddEvenEvenOdd,
    levelNineEvenOddEvenEven,
    levelNineEvenOddEvenOddEvenEven,
    levelNineEvenOddEvenOddEvenOdd,
    levelNineEvenOddEvenOddEven,
    levelNineEvenOddEvenOddOddEven,
    levelNineEvenOddEvenOddOddOdd,
    levelNineEvenOddEvenOddOdd,
    levelNineEvenOddEvenOdd,
    levelNineEvenOddEven,
    levelNineEvenOddOddEvenEvenEven,
    levelNineEvenOddOddEvenEvenOdd,
    levelNineEvenOddOddEvenEven,
    levelNineEvenOddOddEvenOddEven,
    levelNineEvenOddOddEvenOddOdd,
    levelNineEvenOddOddEvenOdd,
    levelNineEvenOddOddEven,
    levelNineEvenOddOddOddEvenEven,
    levelNineEvenOddOddOddEvenOdd,
    levelNineEvenOddOddOddEven,
    levelNineEvenOddOddOddOddEven,
    levelNineEvenOddOddOddOddOdd,
    levelNineEvenOddOddOddOdd,
    levelNineEvenOddOddOdd,
    levelNineEvenOddOdd,
    levelNineEvenOdd,
    levelNineEven,
    levelNineOddEvenEvenEvenEvenEven,
    levelNineOddEvenEvenEvenEvenOdd,
    levelNineOddEvenEvenEvenEven,
    levelNineOddEvenEvenEvenOddEven,
    levelNineOddEvenEvenEvenOddOdd,
    levelNineOddEvenEvenEvenOdd,
    levelNineOddEvenEvenEven,
    levelNineOddEvenEvenOddEvenEven,
    levelNineOddEvenEvenOddEvenOdd,
    levelNineOddEvenEvenOddEven,
    levelNineOddEvenEvenOddOddEven,
    levelNineOddEvenEvenOddOddOdd,
    levelNineOddEvenEvenOddOdd,
    levelNineOddEvenEvenOdd,
    levelNineOddEvenEven,
    levelNineOddEvenOddEvenEvenEven,
    levelNineOddEvenOddEvenEvenOdd,
    levelNineOddEvenOddEvenEven,
    levelNineOddEvenOddEvenOddEven,
    levelNineOddEvenOddEvenOddOdd,
    levelNineOddEvenOddEvenOdd,
    levelNineOddEvenOddEven,
    levelNineOddEvenOddOddEvenEven,
    levelNineOddEvenOddOddEvenOdd,
    levelNineOddEvenOddOddEven,
    levelNineOddEvenOddOddOddEven,
    levelNineOddEvenOddOddOddOdd,
    levelNineOddEvenOddOddOdd,
    levelNineOddEvenOddOdd,
    levelNineOddEvenOdd,
    levelNineOddEven,
    levelNineOddOddEvenEvenEvenEven,
    levelNineOddOddEvenEvenEvenOdd,
    levelNineOddOddEvenEvenEven,
    levelNineOddOddEvenEvenOddEven,
    levelNineOddOddEvenEvenOddOdd,
    levelNineOddOddEvenEvenOdd,
    levelNineOddOddEvenEven,
    levelNineOddOddEvenOddEvenEven,
    levelNineOddOddEvenOddEvenOdd,
    levelNineOddOddEvenOddEven,
    levelNineOddOddEvenOddOddEven,
    levelNineOddOddEvenOddOddOdd,
    levelNineOddOddEvenOddOdd,
    levelNineOddOddEvenOdd,
    levelNineOddOddEven,
    levelNineOddOddOddEvenEvenEven,
    levelNineOddOddOddEvenEvenOdd,
    levelNineOddOddOddEvenEven,
    levelNineOddOddOddEvenOddEven,
    levelNineOddOddOddEvenOddOdd,
    levelNineOddOddOddEvenOdd,
    levelNineOddOddOddEven,
    levelNineOddOddOddOddEvenEven,
    levelNineOddOddOddOddEvenOdd,
    levelNineOddOddOddOddEven,
    levelNineOddOddOddOddOddEven,
    levelNineOddOddOddOddOddOdd,
    levelNineOddOddOddOddOdd,
    levelNineOddOddOddOdd,
    levelNineOddOddOdd,
    levelNineOddOdd,
    levelNineOdd,
    levelNine,
    Entries.allLE,
    levelNine_cap_block_0,
    levelNine_cap_block_1,
    levelNine_cap_block_2,
    levelNine_cap_block_3,
    levelNine_cap_block_4,
    levelNine_cap_block_5,
    levelNine_cap_block_6,
    levelNine_cap_block_7,
    levelNine_cap_block_8,
    levelNine_cap_block_9,
    levelNine_cap_block_10,
    levelNine_cap_block_11,
    levelNine_cap_block_12,
    levelNine_cap_block_13,
    levelNine_cap_block_14,
    levelNine_cap_block_15,
    levelNine_cap_block_16,
    levelNine_cap_block_17,
    levelNine_cap_block_18,
    levelNine_cap_block_19,
    levelNine_cap_block_20,
    levelNine_cap_block_21,
    levelNine_cap_block_22,
    levelNine_cap_block_23,
    levelNine_cap_block_24,
    levelNine_cap_block_25,
    levelNine_cap_block_26,
    levelNine_cap_block_27,
    levelNine_cap_block_28,
    levelNine_cap_block_29,
    levelNine_cap_block_30,
    levelNine_cap_block_31,
    levelNine_cap_block_32,
    levelNine_cap_block_33,
    levelNine_cap_block_34,
    levelNine_cap_block_35,
    levelNine_cap_block_36,
    levelNine_cap_block_37,
    levelNine_cap_block_38,
    levelNine_cap_block_39,
    levelNine_cap_block_40,
    levelNine_cap_block_41,
    levelNine_cap_block_42,
    levelNine_cap_block_43,
    levelNine_cap_block_44,
    levelNine_cap_block_45,
    levelNine_cap_block_46,
    levelNine_cap_block_47,
    levelNine_cap_block_48,
    levelNine_cap_block_49,
    levelNine_cap_block_50,
    levelNine_cap_block_51,
    levelNine_cap_block_52,
    levelNine_cap_block_53,
    levelNine_cap_block_54,
    levelNine_cap_block_55,
    levelNine_cap_block_56,
    levelNine_cap_block_57,
    levelNine_cap_block_58,
    levelNine_cap_block_59,
    levelNine_cap_block_60,
    levelNine_cap_block_61,
    levelNine_cap_block_62,
    levelNine_cap_block_63,
    levelNine_cap_block_64,
    levelNine_cap_block_65,
    levelNine_cap_block_66,
    levelNine_cap_block_67,
    levelNine_cap_block_68,
    levelNine_cap_block_69,
    levelNine_cap_block_70,
    levelNine_cap_block_71,
    levelNine_cap_block_72,
    levelNine_cap_block_73,
    levelNine_cap_block_74,
    levelNine_cap_block_75,
    levelNine_cap_block_76,
    levelNine_cap_block_77,
    levelNine_cap_block_78,
    levelNine_cap_block_79,
    levelNine_cap_block_80,
    levelNine_cap_block_81,
    levelNine_cap_block_82,
    levelNine_cap_block_83,
    levelNine_cap_block_84,
    levelNine_cap_block_85,
    levelNine_cap_block_86,
    levelNine_cap_block_87,
    levelNine_cap_block_88,
    levelNine_cap_block_89,
    levelNine_cap_block_90,
    levelNine_cap_block_91,
    levelNine_cap_block_92,
    levelNine_cap_block_93,
    levelNine_cap_block_94,
    levelNine_cap_block_95,
    levelNine_cap_block_96,
    levelNine_cap_block_97,
    levelNine_cap_block_98,
    levelNine_cap_block_99,
    levelNine_cap_block_100,
    levelNine_cap_block_101,
    levelNine_cap_block_102,
    levelNine_cap_block_103,
    levelNine_cap_block_104,
    levelNine_cap_block_105,
    levelNine_cap_block_106,
    levelNine_cap_block_107,
    levelNine_cap_block_108,
    levelNine_cap_block_109,
    levelNine_cap_block_110,
    levelNine_cap_block_111,
    levelNine_cap_block_112,
    levelNine_cap_block_113,
    levelNine_cap_block_114,
    levelNine_cap_block_115,
    levelNine_cap_block_116,
    levelNine_cap_block_117,
    levelNine_cap_block_118,
    levelNine_cap_block_119,
    levelNine_cap_block_120,
    levelNine_cap_block_121,
    levelNine_cap_block_122,
    levelNine_cap_block_123,
    levelNine_cap_block_124,
    levelNine_cap_block_125,
    levelNine_cap_block_126,
    levelNine_cap_block_127,
    Bool.and_self]
/-- Exact finite certificate for the stated depth-nine range or bound. -/
theorem levelNine_max_comparison : 15784016688259364 ≤ 57 * 2^48 := by decide +kernel
end WordCertDensity.Certificates
